version: '2'
services:
  queue-rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    restart: always
    #volumes:
      #- ./database:/data
    ports:
      - "5672:5672"
  queue:
    image: arijmansour/pfe_queue_microservices:latest
    hostname: pfe_queue_microservices
    restart: always
    ports:
      - "8084:80"
